export type Color =
  | "primary"
  | "info"
  | "success"
  | "danger"
  | "warning"
  | "default"
  | "secondary"
  | "gray1"
  | "gray2"
  | "gray3"
  | "gray4"
  | "gray5"
  | "gray6"
  | "gray7"
  | "gray8"
  | "gray9"
  | "white"
  | "transparent"

export type Align = "left" | "center" | "right"

export type Size = "default" | "medium" | "large"
